language: cpp
jobs:
  include:
    - name: Linux
      dist: focal
      compiler:
        - gcc
      os:
        - linux
      addons:
        apt:
          packages:
            - cmake
            - ninja-build

      before_install:
        - echo $LANG
        - echo $LC_ALL
      script:
        - bash scripts/build.sh
      after_success:
        - cd build
        - ctest -VV
      env:
        global:
          - LANG="en_US.UTF-8"

